### ISSUE TITLE
"double" posting to emulator when attempting UpdateCardMsgDialog.cs

### ISSUE THREAD

**Issue by ileonc** [OfficeDev/microsoft-teams-sample-complete-csharp#25]
Hi, I'm seeing a strange behaviour when the bot emulator runs the UpdateCardMsgSetupDialog.cs.  The bot emulator shows two messages being posted - 
![image](https://user-images.githubusercontent.com/44498847/49870218-07977400-fe13-11e8-945b-3b20337bc555.png)
The first <-message shows the correct timestamp and an ID:
![image](https://user-images.githubusercontent.com/44498847/49870268-2a298d00-fe13-11e8-82cf-9435cf4f2314.png)

The second POST 200 shows no ID and a different timezone:
![image](https://user-images.githubusercontent.com/44498847/49870322-4f1e0000-fe13-11e8-959a-e3140a22f47e.png)

It renders the card, the button renders but does nothing, and the text is there but cannot be changed.
![image](https://user-images.githubusercontent.com/44498847/49870354-6a890b00-fe13-11e8-973b-017d77e86d18.png)
I tried from the GIT example here and then pulled the code into a "clean" VS project and I still get the same symptoms. 
Can someone give me a hand? Or is this an easy fix?

**Comment by ileonc** [comment]
And I'm running it all on my local PC, no ngrok intervention. Thanks,

**Comment by jotrick** [comment]
Hi ileonc - this specific project is targeted at running the bot in the Teams app. There are some things that do work in the Emulator, but for certain things (specifically here with updating messages), they will only work in the Teams app. I would suggest getting your bot to work in the Teams app and looking at the functionality there.
