### ISSUE TITLE
Nodejs sample similar to microsoft-teams-sample-complete-csharp 

### ISSUE THREAD

**Issue by rjgmail88** [OfficeDev/microsoft-teams-sample-complete-csharp#30]
Is there any nodejs BOT SDK v4 sample that is equivalent to this sample microsoft-teams-sample-complete-csharp ?

**Comment by clearab** [comment]
Teams functionality will be available in the 4.6 release of the Bot Framework SDK, which is releasing shortly. Full documentation and samples are currently being built, however you can view early versions here: https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/teams/js
